import os
import base64
import requests
from dotenv import load_dotenv

load_dotenv()

def inject_blog_page():
    token = os.getenv("GITHUB_TOKEN")
    repo = os.getenv("GITHUB_REPO")
    # 我们在 pages 目录下创建一个 blog.js 文件
    file_path = "pages/blog.js" 
    
    print(f"🚀 大龙虾正在为官网注入博客页面逻辑...")

    # 这是一个极简但专业的 React 代码，它会自动读取仓库里的 blog-post.md
    blog_page_code = """
import React, { useEffect, useState } from 'react';
import ReactMarkdown from 'react-markdown';

export default function Blog() {
  const [content, setContent] = useState('Loading latest insights...');

  useEffect(() => {
    fetch('https://raw.githubusercontent.com/""" + repo + """/main/blog-post.md')
      .then(res => res.text())
      .then(text => setContent(text))
      .catch(err => setContent('Failed to load blog content.'));
  }, []);

  return (
    <div style={{ maxWidth: '800px', margin: '0 auto', padding: '40px', fontFamily: 'sans-serif', lineHeight: '1.6' }}>
      <a href="/" style={{ color: '#666', textDecoration: 'none' }}>← Back to Home</a>
      <div style={{ marginTop: '20px', borderTop: '1px solid #eee', paddingTop: '20px' }}>
        <ReactMarkdown>{content}</ReactMarkdown>
      </div>
      <footer style={{ marginTop: '40px', fontSize: '12px', color: '#999' }}>
        Generated by OpenClaw AI for SeekAPI.ai
      </footer>
    </div>
  );
}
"""

    url = f"https://api.github.com/repos/{repo}/contents/{file_path}"
    headers = {"Authorization": f"Bearer {token}", "Accept": "application/vnd.github+json"}
    
    # 检查是否已存在
    res = requests.get(url, headers=headers)
    sha = res.json().get('sha') if res.status_code == 200 else None

    # 提交代码
    encoded_content = base64.b64encode(blog_page_code.encode('utf-8')).decode('utf-8')
    data = {
        "message": "🤖 OpenClaw: 激活 /blog 自动化页面",
        "content": encoded_content
    }
    if sha: data["sha"] = sha

    put_res = requests.put(url, json=data, headers=headers)
    
    if put_res.status_code in [200, 201]:
        print("✅ 博客页面代码注入成功！")
        print("⏳ Vercel 正在重新构建网站，请等待约 2 分钟...")
    else:
        print(f"❌ 注入失败: {put_res.text}")

if __name__ == "__main__":
    inject_blog_page()
