import os
import base64
import requests
from dotenv import load_dotenv

load_dotenv()

def deploy_static_blog():
    token = os.getenv("GITHUB_TOKEN")
    repo = os.getenv("GITHUB_REPO")
    # 路径设为 public/blog/index.html
    # 这样访问 seekapi.ai/blog/ 就会直接看到它
    file_path = "public/blog/index.html"
    
    print(f"🚀 正在通过静态路径部署博客，绕过 Vercel 编译逻辑...")

    # 这是一个自包含的 HTML，自带 Markdown 解析功能
    html_code = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SeekAPI Blog - AI Insights</title>
    <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
    <style>
        body { font-family: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", Roboto; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 40px; }
        a { color: #0070f3; text-decoration: none; }
        .header { border-bottom: 1px solid #eee; padding-bottom: 20px; margin-bottom: 30px; }
        #content { background: #fff; }
        pre { background: #f4f4f4; padding: 15px; border-radius: 5px; overflow-x: auto; }
        code { font-family: monospace; }
    </style>
</head>
<body>
    <div class="header">
        <a href="/">← Back to SeekAPI Home</a>
    </div>
    <div id="content">Loading latest AI insights...</div>
    <script>
        fetch('https://raw.githubusercontent.com/""" + repo + """/main/blog-post.md')
            .then(response => response.text())
            .then(text => {
                document.getElementById('content').innerHTML = marked.parse(text);
            })
            .catch(err => {
                document.getElementById('content').innerHTML = 'Blog content is being generated by OpenClaw... Please refresh in a minute.';
            });
    </script>
</body>
</html>
"""

    url = f"https://api.github.com/repos/{repo}/contents/{file_path}"
    headers = {"Authorization": f"Bearer {token}", "Accept": "application/vnd.github+json"}
    
    res = requests.get(url, headers=headers)
    sha = res.json().get('sha') if res.status_code == 200 else None

    encoded_content = base64.b64encode(html_code.encode('utf-8')).decode('utf-8')
    data = {
        "message": "🤖 OpenClaw: 部署静态博客页 (绕过编译)",
        "content": encoded_content
    }
    if sha: data["sha"] = sha

    put_res = requests.put(url, json=data, headers=headers)
    
    if put_res.status_code in [200, 201]:
        print("✅ 静态页面已推送到 GitHub！")
        print("🔗 请在 1 分钟后访问：https://seekapi.ai/blog/index.html")
        print("💡 或者尝试：https://seekapi.ai/blog/")
    else:
        print(f"❌ 部署失败: {put_res.text}")

if __name__ == "__main__":
    deploy_static_blog()
