import os, base64, requests
from dotenv import load_dotenv

load_dotenv()

def push_to_github(path, content, message):
    token = os.getenv("GITHUB_TOKEN")
    repo = os.getenv("GITHUB_REPO")
    url = f"https://api.github.com/repos/{repo}/contents/{path}"
    headers = {"Authorization": f"Bearer {token}", "Accept": "application/vnd.github+json"}
    res = requests.get(url, headers=headers)
    sha = res.json().get('sha') if res.status_code == 200 else None
    data = {"message": message, "content": base64.b64encode(content.encode('utf-8')).decode('utf-8')}
    if sha: data["sha"] = sha
    requests.put(url, json=data, headers=headers)
    print(f"✅ 资产已加固: {path}")

# --- 1. 终极版 Terms of Service (Chief Justice Standard) ---
tos = """
<h1>Terms of Service</h1>
<p>Last Updated: March 13, 2026</p>
<p>This Agreement is a legally binding contract between you ("User", "Customer", or "Developer") and <b>SeekAPI Global (Hong Kong) Limited</b> ("Company", "SeekAPI", "we", "us").</p>

<h3>1. ACCEPTANCE OF TERMS</h3>
<p>By accessing the SeekAPI.ai gateway, API endpoints, or dashboard, you irrevocably agree to be bound by these Terms, our Privacy Policy, and our Acceptable Use Policy. If you are entering into this agreement on behalf of a company, you represent that you have the legal authority to bind that entity.</p>

<h3>2. THE "MERE CONDUIT" DOCTRINE (HKSAR Cap. 553)</h3>
<p>SeekAPI.ai operates strictly as a technical intermediary. Pursuant to the <b>Electronic Transactions Ordinance (Cap. 553)</b> of the Hong Kong Special Administrative Region, SeekAPI acts as a <b>"Mere Conduit."</b> We do not: (i) initiate the transmission; (ii) select the receiver of the transmission; or (iii) select or modify the information contained in the transmission. We exercise zero editorial control over the content generated by third-party Large Language Models (LLMs).</p>

<h3>3. MANDATORY DATA SANITIZATION & DE-IDENTIFICATION</h3>
<p><b>User Warranty:</b> You represent and warrant that you shall NOT transmit any Personal Identifiable Information (PII), sensitive financial data (including PCI-DSS regulated data), health records (HIPAA), or any data protected under global privacy laws (GDPR, CCPA, PDPO) through the Service without prior <b>DE-IDENTIFICATION, ANONYMIZATION, and ENCRYPTION</b>. SeekAPI does not inspect data payloads; the absolute burden of data scrubbing lies with the User. You agree to indemnify SeekAPI for any breach of this clause.</p>

<h3>4. PROHIBITED USE CASES (ZERO TOLERANCE)</h3>
<p>You are strictly prohibited from using the Service for: (a) Any activity violating HKSAR laws or international sanctions; (b) Developing, training, or improving competing AI models; (c) Generating deceptive content (Deepfakes), non-consensual sexual content, or hate speech; (d) High-risk financial analysis, unauthorized credit scoring, or market manipulation; (e) Any use case involving autonomous weaponry, mass surveillance, or critical infrastructure control.</p>

<h3>5. LIMITATION OF LIABILITY & TOTAL INDEMNIFICATION</h3>
<p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, SEEKAPI SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOSS OF PROFITS, REVENUE, OR DATA. OUR TOTAL AGGREGATE LIABILITY SHALL NOT EXCEED THE TOTAL FEES PAID BY YOU IN THE THREE (3) MONTHS PRECEDING THE CLAIM. YOU AGREE TO DEFEND AND HOLD HARMLESS SEEKAPI GLOBAL (HK) LTD FROM ANY CLAIMS ARISING FROM YOUR MISUSE OF AI-GENERATED OUTPUTS.</p>

<h3>6. GOVERNING LAW & JURISDICTION</h3>
<p>These Terms are governed by the laws of the <b>Hong Kong Special Administrative Region</b>. Any dispute, controversy, or claim arising out of this Agreement shall be referred to and finally resolved by the exclusive jurisdiction of the Courts of the Hong Kong SAR.</p>
"""

# --- 2. 终极版 Privacy Policy (PDPO Standard) ---
privacy = """
<h1>Privacy Policy</h1>
<p>Last Updated: March 13, 2026</p>
<p>SeekAPI Global (HK) Ltd complies with the <b>Personal Data (Privacy) Ordinance (Cap. 486)</b> of Hong Kong.</p>

<h3>1. ZERO-RETENTION PAYLOAD POLICY</h3>
<p>SeekAPI.ai implements a strict <b>Zero-Retention Policy</b> for API request and response payloads. We do NOT store, log, or cache the content of your prompts or the resulting AI completions. Data is processed in volatile memory and streamed directly to upstream providers. We do not use customer data to train or fine-tune AI models.</p>

<h3>2. METADATA COLLECTION</h3>
<p>We collect minimal metadata necessary for service delivery: (a) Account email for authentication; (b) Billing metadata for Stripe processing; (c) Technical logs (IP addresses, timestamps) for DDoS mitigation and rate-limiting. These logs are encrypted and automatically purged every 14 days.</p>

<h3>3. THIRD-PARTY PROCESSORS (STRIPE)</h3>
<p>Payment processing is handled exclusively by <b>Stripe, Inc.</b>. SeekAPI does not store credit card numbers, CVVs, or full billing addresses on our infrastructure. Your financial data is subject to Stripe's Global Privacy Policy.</p>

<h3>4. INTERNATIONAL DATA TRANSFERS</h3>
<p>By using our Service, you acknowledge that data may be routed through international data centers to optimize latency. All transfers are conducted using industry-standard TLS 1.3 encryption.</p>
"""

# --- 3. 终极版 Refund Policy (Stripe Compliance) ---
refund = """
<h1>Refund & Billing Policy</h1>
<p>Last Updated: March 13, 2026</p>

<h3>1. PRE-PAID CREDIT SYSTEM</h3>
<p>SeekAPI.ai operates on a pre-paid credit model. Credits are deducted in real-time based on token consumption as reported by upstream providers. 1 USD is equivalent to 500,000 standard credits, subject to model-specific multipliers.</p>

<h3>2. 7-DAY REFUND GUARANTEE</h3>
<p>We offer a <b>7-day money-back guarantee</b> for the <b>UNUSED and UNCONSUMED</b> balance of your initial purchase. If you are unsatisfied with the service quality, you may request a refund by contacting support@seekapi.ai within 7 days of the transaction date.</p>

<h3>3. NON-REFUNDABLE ITEMS</h3>
<p>Credits that have already been consumed for successful API calls (HTTP 200) are strictly non-refundable. Promotional credits, bonus balances, and trial credits have no cash value and cannot be refunded.</p>

<h3>4. CHARGEBACK & FRAUD PREVENTION</h3>
<p>Unauthorized chargebacks will result in immediate account termination and permanent blacklisting. SeekAPI reserves the right to pursue legal action in the HKSAR to recover funds lost through fraudulent chargebacks.</p>
"""

# --- 4. 终极黑金页脚 ---
footer = '<div id="openclaw-injected" style="font-family:sans-serif; width:100%;"><footer style="background:#000; padding:60px 20px; text-align:center; border-top:1px solid #111; color:#fff;"><div style="margin-bottom:30px;"><a href="/terms" style="margin:0 15px; color:#888; text-decoration:none;">Terms</a><a href="/privacy" style="margin:0 15px; color:#888; text-decoration:none;">Privacy</a><a href="/refund" style="margin:0 15px; color:#888; text-decoration:none;">Refund</a><a href="/insights" style="margin:0 15px; color:#2563eb; text-decoration:none; font-weight:bold;">AION Insights</a></div><div style="margin-bottom:30px;"><p style="color:#444; font-size:12px; text-transform:uppercase; letter-spacing:2px;">Developer Ecosystem</p><a href="https://github.com/kiddhu/aion-bench" target="_blank" style="margin:0 10px; color:#fff; text-decoration:none;">⭐ AION-Bench</a><a href="https://github.com/kiddhu/aion-sdk-python" target="_blank" style="margin:0 10px; color:#fff; text-decoration:none;">📦 AION-SDK</a></div><p style="color:#6b7280; font-size:12px;">© 2026 SeekAPI.ai | AION: The Era of the One.</p><p style="color:#444; font-size:11px;">Unit 1603, 16/F, The Metropolis Tower, Hong Kong</p></footer></div>'

push_to_github("assets/legal_terms.html", tos, "Bulletproof Legal V13")
push_to_github("assets/legal_privacy.html", privacy, "Bulletproof Legal V13")
push_to_github("assets/legal_refund.html", refund, "Bulletproof Legal V13")
push_to_github("assets/footer.html", footer, "Locking Footer V13")
