import os
import requests
import base64
from dotenv import load_dotenv

load_dotenv()

def find_and_sync():
    token = os.getenv("GITHUB_TOKEN")
    # 1. 先获取你的 GitHub 用户名
    user_res = requests.get("https://api.github.com/user", headers={"Authorization": f"Bearer {token}"})
    username = user_res.json().get('login')
    print(f"👤 检测到 GitHub 用户: {username}")

    # 2. 列出你所有的仓库，寻找 v0 开头的那个
    repo_res = requests.get(f"https://api.github.com/user/repos?per_page=100&sort=updated", headers={"Authorization": f"Bearer {token}"})
    repos = repo_res.json()
    
    target_repo = None
    print("🔍 正在扫描你的仓库列表...")
    for r in repos:
        name = r['full_name']
        # 寻找包含 v0 且最近更新的仓库
        if "v0-" in name.lower():
            target_repo = name
            print(f"🎯 找到疑似真身: {target_repo}")
            break
    
    if not target_repo:
        print("❌ 未找到 v0 开头的仓库。请手动去 GitHub 确认仓库全名。")
        return

    # 3. 准备要推送的内容
    # 我们直接把博客内容嵌入到 HTML 里，这样最稳，不需要读取外部 md 文件
    blog_content = "<h1>How to Slash Your AI Inference Costs by 90%</h1><p>Using DeepSeek R1 and SeekAPI.ai, developers are saving thousands...</p>"
    
    html_code = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8"><title>SeekAPI Blog</title>
    <style>body{{font-family:sans-serif;line-height:1.6;max-width:800px;margin:0 auto;padding:50px;}}</style>
</head>
<body>
    <a href="/">← Back</a>
    <hr>
    {blog_content}
    <p style="color:gray;font-size:12px;">Auto-generated by OpenClaw AI</p>
</body>
</html>
"""

    # 4. 推送到真仓库的 public/blog/index.html
    file_path = "public/blog/index.html"
    url = f"https://api.github.com/repos/{target_repo}/contents/{file_path}"
    headers = {"Authorization": f"Bearer {token}", "Accept": "application/vnd.github+json"}
    
    # 获取 SHA
    res = requests.get(url, headers=headers)
    sha = res.json().get('sha') if res.status_code == 200 else None

    data = {
        "message": "🤖 OpenClaw: 自动同步博客到真仓库",
        "content": base64.b64encode(html_code.encode()).decode()
    }
    if sha: data["sha"] = sha

    put_res = requests.put(url, json=data, headers=headers)
    
    if put_res.status_code in [200, 201]:
        print(f"✅ 成功！博客已推送到真仓库: {target_repo}")
        print(f"🚀 请在 1 分钟后访问: https://seekapi.ai/blog/")
        # 顺便更新 .env 以后就不用再找了
        os.system(f"sed -i 's|GITHUB_REPO=.*|GITHUB_REPO={target_repo}|' .env")
    else:
        print(f"❌ 部署失败: {put_res.text}")

if __name__ == "__main__":
    find_and_sync()
