
import React, { useEffect, useState } from 'react';
import ReactMarkdown from 'react-markdown';

export default function Blog() {
  const [content, setContent] = useState('Loading latest insights...');

  useEffect(() => {
    fetch('https://raw.githubusercontent.com/kiddhu/deepseek-global-wrapper/main/blog-post.md')
      .then(res => res.text())
      .then(text => setContent(text))
      .catch(err => setContent('Failed to load blog content.'));
  }, []);

  return (
    <div style={{ maxWidth: '800px', margin: '0 auto', padding: '40px', fontFamily: 'sans-serif', lineHeight: '1.6' }}>
      <a href="/" style={{ color: '#666', textDecoration: 'none' }}>← Back to Home</a>
      <div style={{ marginTop: '20px', borderTop: '1px solid #eee', paddingTop: '20px' }}>
        <ReactMarkdown>{content}</ReactMarkdown>
      </div>
      <footer style={{ marginTop: '40px', fontSize: '12px', color: '#999' }}>
        Generated by OpenClaw AI for SeekAPI.ai
      </footer>
    </div>
  );
}
